### ISSUE TITLE
Where is semp_jaxb/r8_6VMR?

### ISSUE THREAD

**Issue by jiang-wei** [koverton/solace-monitoring-extension#1]
in this repo https://github.com/koverton/semp_jaxb
I can not find the latest xsd for the latest SEMP schema
How did you compile semp_jaxb_8_6VMR.pom?

I'm using SEMP with version soltr/8_11VMR which seems a little different than 8_6VMR
do you have the latest version of the xsd?

**Comment by koverton** [comment]
Just noticed this; I've uploaded it to the mvn_libs directory thanks for pointing it out. I also ship it with all the releases so you could retrieve it from the latest release zip.
